insulate("Check traffic light sequence", function ()
    require("ce.hub.eep.EepSimulator")
    local ModuleRegistry = require("ce.hub.ModuleRegistry")
    local crossingCeModule = require("ce.mods.road.CeRoadModule")
    ModuleRegistry.registerModules(crossingCeModule)

    local modNames = ModuleRegistry.getModuleNames()
    it("modNames size  ", function () assert.equals(2, #modNames) end)
    it("Hub first!     ", function () assert.equals("ce.hub.CeHubModule", modNames[1]) end)
    it("Road second!   ", function () assert.equals("ce.mods.road.CeRoadModule", modNames[2]) end)
end)
