describe("ce.hub.util.StorageUtility", function ()
    insulate("can be loaded with debug off", function ()
        require("ce.hub.eep.EepSimulator")
        EEPSaveData(1, true)
        EEPSaveData(2, false)
        EEPSaveData(3, "true")
        EEPSaveData(4, "false")
        EEPSaveData(5, 5)
        EEPSaveData(6, 6)
        EEPSaveData(7, "5")
        EEPSaveData(8, "6")
        local StorageUtility = require("ce.hub.util.StorageUtility")
        it("Debug is off", function () assert.is_false(StorageUtility.debug) end)
    end)
    insulate("boolean true is stored as 1", function ()
        require("ce.hub.eep.EepSimulator")
        EEPSaveData(1, true)
        local StorageUtility = require("ce.hub.util.StorageUtility")
        it("calculateEepLuaData()",
           function () assert.equals("[EEPLuaData]\nDB_1 = 1\n", StorageUtility.calcEepLuaData()) end)
    end)
    insulate("boolean false is stored as 0", function ()
        require("ce.hub.eep.EepSimulator")
        EEPSaveData(2, false)
        local StorageUtility = require("ce.hub.util.StorageUtility")
        it("calculateEepLuaData()",
           function () assert.equals("[EEPLuaData]\nDB_2 = 0\n", StorageUtility.calcEepLuaData()) end)
    end)
    insulate("string true is stored as true", function ()
        require("ce.hub.eep.EepSimulator")
        EEPSaveData(3, "true")
        local StorageUtility = require("ce.hub.util.StorageUtility")
        it("calculateEepLuaData()",
           function () assert.equals("[EEPLuaData]\nDS_3 = \"true\"\n", StorageUtility.calcEepLuaData()) end)
    end)
    insulate("encoded table length", function ()
        require("ce.hub.eep.EepSimulator")
        local StorageUtility = require("ce.hub.util.StorageUtility")

        it("uses the same key-value framing as encodeTable", function ()
            assert.equals(10, StorageUtility.encodedTableLength({ a = "1", bb = "22" }))
            assert.equals("a=1,bb=22,", StorageUtility.encodeTable({ a = "1", bb = "22" }))
        end)

        it("encodes with a shrinking value when the original table is too long", function ()
            local data = {
                a = "1",
                q = "one|two|three"
            }
            local function shrinkQueueText(value)
                return string.match(value, "^(.*)|[^|]*$")
            end

            assert.equals("a=1,q=one,", StorageUtility.encodeTableWithShrinkingValue(data, "q", shrinkQueueText, 12))
            assert.equals("one|two|three", data.q)
        end)
    end)
    insulate("number 5 is stored as 5.000000", function ()
        require("ce.hub.eep.EepSimulator")
        EEPSaveData(5, 5)
        local StorageUtility = require("ce.hub.util.StorageUtility")
        it("calculateEepLuaData()",
           function () assert.equals("[EEPLuaData]\nDN_5 = 5.000000\n", StorageUtility.calcEepLuaData()) end)
    end)
end)
