read_globals = {
    "AkDebugLoad",
    "CeDebugLoad",
    "CeStartWithDebug",
    "CeTestingMode",
    "EEPActivateCtrlDesk",
    "EEPAuxiliaryTackGetTextureText",
    "EEPAuxiliaryTackSetTextureText",
    "EEPAuxiliaryTrackChangeAppearance",
    "EEPAuxiliaryTrackGetTextureText",
    "EEPAuxiliaryTrackSetTextureText",
    "EEPChangeInfoSignal",
    "EEPChangeInfoStructure",
    "EEPChangeInfoSwitch",
    "EEPCheckSetRoute",
    "EEPGetAnlLng",
    "EEPGetAnlName",
    "EEPGetAnlPath",
    "EEPGetAnlVer",
    "EEPGetCameraPosition",
    "EEPGetCameraRotation",
    "EEPGetCloudsIntensity",
    "EEPGetCloudsMode",
    "EEPGetCurrentFrame",
    "EEPGetCurrentRenderFrame",
    "EEPGetFogIntensity",
    "EEPGetFramesPerSecond",
    "EEPGetHailIntensity",
    "EEPGetPerspectiveCamera",
    "EEPGetRainIntensity",
    "EEPGetRollingstockItemName",
    "EEPGetRollingstockItemsCount",
    "EEPGetSeason",
    "EEPGetSignal",
    "EEPGetSignalFunction",
    "EEPGetSignalFunctions",
    "EEPGetSignalItemName",
    "EEPGetSignalStopDistance",
    "EEPGetSignalTrainName",
    "EEPGetSignalTrainsCount",
    "EEPGetSnowIntensity",
    "EEPGetSwitch",
    "EEPGetTimeLapse",
    "EEPGetTrainActive",
    "EEPGetTrainCouplingFront",
    "EEPGetTrainCouplingRear",
    "EEPGetTrainFromTrainyard",
    "EEPGetTrainLength",
    "EEPGetTrainLight",
    "EEPGetTrainRoute",
    "EEPGetTrainSpeed",
    "EEPGetTrainyardItemName",
    "EEPGetTrainyardItemStatus",
    "EEPGetTrainyardItemsCount",
    "EEPGetWindIntensity",
    "EEPGetZoneClouds",
    "EEPGetZoneFogIntensity",
    "EEPGetZoneHailIntensity",
    "EEPGetZonePos",
    "EEPGetZoneRainIntensity",
    "EEPGetZoneSnowIntensity",
    "EEPGetZoneWindIntensity",
    "EEPGoodsGetAxis",
    "EEPGoodsGetAxisByNumber",
    "EEPGoodsGetModelType",
    "EEPGoodsGetPosition",
    "EEPGoodsGetRotation",
    "EEPGoodsGetTagText",
    "EEPGoodsGetTextureText",
    "EEPGoodsSetAxis",
    "EEPGoodsSetAxisByNumber",
    "EEPGoodsSetAxisByNumer",
    "EEPGoodsSetPosition",
    "EEPGoodsSetRotation",
    "EEPGoodsSetTagText",
    "EEPGoodsSetTextureText",
    "EEPHideInfoTextBottom",
    "EEPHideInfoTextTop",
    "EEPIsAuxiliaryTrackReserved",
    "EEPIsControlTrackReserved",
    "EEPIsRailTrackReserved",
    "EEPIsRoadTrackReserved",
    "EEPIsTrainInTrainyard",
    "EEPIsTramTrackReserved",
    "EEPLng",
    "EEPLoadData",
    "EEPLoadProject",
    "EEPMain",
    "EEPOnBeforeSaveAnl",
    "EEPOnSaveAnl",
    "EEPOnSignal_x",
    "EEPOnSwitch_x",
    "EEPOnTrainCoupling",
    "EEPOnTrainEnterTrainyard",
    "EEPOnTrainExitTrainyard",
    "EEPOnTrainLooseCoupling",
    "EEPOnTrainStoppedOnSignal",
    "EEPPause",
    "EEPPlaySound",
    "EEPPutTrainToTrainyard",
    "EEPRailTrackChangeAppearance",
    "EEPRailTrackGetTextureText",
    "EEPRailTrackSetTextureText",
    "EEPRegisterAuxiliaryTrack",
    "EEPRegisterControlTrack",
    "EEPRegisterRailTrack",
    "EEPRegisterRoadTrack",
    "EEPRegisterSignal",
    "EEPRegisterSwitch",
    "EEPRegisterTramTrack",
    "EEPRoadTrackChangeAppearance",
    "EEPRoadTrackGetTextureText",
    "EEPRoadTrackSetTextureText",
    "EEPRollingstockChangeOrientation",
    "EEPRollingstockGetActive",
    "EEPRollingstockGetAxis",
    "EEPRollingstockGetAxisByNumber",
    "EEPRollingstockGetCouplingFront",
    "EEPRollingstockGetCouplingRear",
    "EEPRollingstockGetHook",
    "EEPRollingstockGetHookGlue",
    "EEPRollingstockGetHookPosition",
    "EEPRollingstockGetLength",
    "EEPRollingstockGetMileage",
    "EEPRollingstockGetModelType",
    "EEPRollingstockGetMotor",
    "EEPRollingstockGetOrientation",
    "EEPRollingstockGetPosition",
    "EEPRollingstockGetRotation",
    "EEPRollingstockGetSmoke",
    "EEPRollingstockGetTagText",
    "EEPRollingstockGetTextureText",
    "EEPRollingstockGetTrack",
    "EEPRollingstockGetTrainName",
    "EEPRollingstockGetUserCamera",
    "EEPRollingstockSetActive",
    "EEPRollingstockSetAxis",
    "EEPRollingstockSetAxisByNumber",
    "EEPRollingstockSetCouplingFront",
    "EEPRollingstockSetCouplingRear",
    "EEPRollingstockSetHook",
    "EEPRollingstockSetHookGlue",
    "EEPRollingstockSetHorn",
    "EEPRollingstockSetSlot",
    "EEPRollingstockSetSmoke",
    "EEPRollingstockSetTagText",
    "EEPRollingstockSetTextureText",
    "EEPRollingstockSetUserCamera",
    "EEPSaveData",
    "EEPSetCamera",
    "EEPSetCameraPosition",
    "EEPSetCameraRotation",
    "EEPSetCloudsIntensity",
    "EEPSetColourFilter",
    "EEPSetDarkCloudsIntensity",
    "EEPSetFogIntensity",
    "EEPSetHailIntensity",
    "EEPSetPerspectiveCamera",
    "EEPSetSeason",
    "EEPSetSignal",
    "EEPSetSignalStopDistance",
    "EEPSetSnowIntensity",
    "EEPSetSwitch",
    "EEPSetTime",
    "EEPSetTrainActive",
    "EEPSetTrainAxis",
    "EEPSetTrainCouplingFront",
    "EEPSetTrainCouplingRear",
    "EEPSetTrainHook",
    "EEPSetTrainHookGlue",
    "EEPSetTrainHorn",
    "EEPSetTrainLight",
    "EEPSetTrainName",
    "EEPSetTrainRoute",
    "EEPSetTrainSmoke",
    "EEPSetTrainSpeed",
    "EEPSetWindIntensity",
    "EEPSetZoneClouds",
    "EEPSetZoneFogIntensity",
    "EEPSetZoneHailIntensity",
    "EEPSetZonePos",
    "EEPSetZoneRainIntensity",
    "EEPSetZoneSnowIntensity",
    "EEPSetZoneWindIntensity",
    "EEPShowInfoSignal",
    "EEPShowInfoStructure",
    "EEPShowInfoSwitch",
    "EEPShowInfoTextBottom",
    "EEPShowInfoTextTop",
    "EEPShowScrollInfoTextBottom",
    "EEPShowScrollInfoTextTop",
    "EEPSignalGetTagText",
    "EEPSignalGetTextureText",
    "EEPSignalSetTagText",
    "EEPSignalSetTextureText",
    "EEPSructureSetAxisByNumer",
    "EEPStructureAnimateAxis",
    "EEPStructureGetAxis",
    "EEPStructureGetAxisByNumber",
    "EEPStructureGetFire",
    "EEPStructureGetLight",
    "EEPStructureGetModelType",
    "EEPStructureGetPosition",
    "EEPStructureGetRotation",
    "EEPStructureGetSmoke",
    "EEPStructureGetTagText",
    "EEPStructureGetTextureText",
    "EEPStructureIsAxisAnimate",
    "EEPStructurePlaySound",
    "EEPStructureSetAxis",
    "EEPStructureSetAxisByNumber",
    "EEPStructureSetFire",
    "EEPStructureSetLight",
    "EEPStructureSetLightingColour",
    "EEPStructureSetLightningColour",
    "EEPStructureSetPosition",
    "EEPStructureSetRotation",
    "EEPStructureSetSmoke",
    "EEPStructureSetTagText",
    "EEPStructureSetTextureText",
    "EEPSwitchGetTagText",
    "EEPSwitchSetTagText",
    "EEPTime",
    "EEPTimeH",
    "EEPTimeM",
    "EEPTimeS",
    "EEPTrainChangeOrientation",
    "EEPTrainLooseCoupling",
    "EEPTramTackGetTextureText",
    "EEPTramTackSetTextureText",
    "EEPTramTrackChangeAppearance",
    "EEPTramTrackGetTextureText",
    "EEPTramTrackSetTextureText",
    "EEPVer",
    "EEPWeb",
    "after_each",
    "before_each",
    "clearlog",
    "describe",
    "finally",
    "insulate",
    "it",
    "pending",
    "print",
    "stub",
}

allow_defined_top = true

-- See https://luacheck.readthedocs.io/en/stable/warnings.html
-- 121 - global assignment to readonly
-- 122 - global field assignment to readonly
-- 131 - global assignment
-- 212 - unused argument
-- 631 - line is too long
files["lua/LUA/ce/hub/eep"].ignore = {"212", "131"}
files["lua/LUA/ce/demo-anlagen"].ignore = {"131"}
files["lua/LUA/ce/hub/CeHubModule.lua"].ignore = {"131"}
files["lua/LUA/ce/hub/mods/CeModule.d.lua"].ignore = {"631"}
files["lua/LUA/ce/mods/road/RoadTypes.d.lua"].ignore = {"631"}
files["lua/LUA/ce/mods/road/data/RoadDtoFactory.lua"].ignore = {"631"}
files["lua/LUA/ce/hub/data/rollingstock/TagKeys.lua"].ignore = {"631"}
files["lua/LUA/ce/hub/data/tracks/TrackDetection.lua"].ignore = {"121", "211"}
files["lua/LUA/ce/hub/data/trains/TrainDetection.lua"].ignore = {"121", "211"}
files["lua/LUA/ce/databridge/LogOutputFileWriter.lua"].ignore = {"111", "113", "121"}
files["lua/LUA/ce/mods/transit/TransitTypes.d.lua"].ignore = {"631"}
files["lua/LUA/ce/hub/data/trains/TrainTypes.d.lua"].ignore = {"631"}
files["lua/LUA/spec/SpecTypes.d.lua"].ignore = {"212"}
files["lua/LUA/spec/ce/hub/data/version/VersionInfo_spec.lua"].ignore = {"122"}
files["lua/LUA/spec/ce/databridge/DataStoreFileWriter_spec.lua"].ignore = {"122"}
files["lua/LUA/spec/ce/databridge/ExchangeDirRegistry_spec.lua"].ignore = {"121", "122"}
files["lua/LUA/spec/ce/databridge/FunctionNameWriter_spec.lua"].ignore = {"122"}
files["lua/LUA/spec/ce/databridge/IncomingCommandFileReader_spec.lua"].ignore = {"122"}
files["lua/LUA/spec/ce/databridge/LogOutputFileWriter_spec.lua"].ignore = {"111", "113", "121", "122"}
files["lua/LUA/spec/ce/databridge/ServerExchangeFileIo_spec.lua"].ignore = {"122"}
files["lua/LUA/spec/ce/hub/data/tracks/TrackDetection_spec.lua"].ignore = {"212"}

exclude_files = {
    ".vscode",
    "assets",
    "docs",
    "lua/LUA/SlotNames_BH2.lua",
    "lua/LUA/ce/third-party/**",
    "lua/LUA/ce/anlagen/**",
    "lua/Resourcen/Anlagen/ce",
    "lua/modell-pakete",
    "scripts",
    "web-app",
    "web-server",
    "web-shared"
}
