import DynamicRoom from './DynamicRoom';

const ApiDataRoom = new DynamicRoom('API Data');
const TrainDetailsRoom = new DynamicRoom('Train Details');
const TrainListRoom = new DynamicRoom('TrainList');
const TransitLineListRoom = new DynamicRoom('Transit List of Lines');
const TransitLineDetailsRoom = new DynamicRoom('Transit Details of Line');
const TransitStationListRoom = new DynamicRoom('Transit List of Stations');
const TransitStationDetailsRoom = new DynamicRoom('Transit Details of Station');
const TransitSettingsRoom = new DynamicRoom('Transit Settings');

const VersionRoom = new DynamicRoom('Version');
const TimeRoom = new DynamicRoom('Time');
const RuntimeRoom = new DynamicRoom('Runtime');
const ModuleRoom = new DynamicRoom('Module');
const SaveSlotRoom = new DynamicRoom('SaveSlot');
const FreeSlotRoom = new DynamicRoom('FreeSlot');
const SignalRoom = new DynamicRoom('Signal');
const WaitingOnSignalRoom = new DynamicRoom('WaitingOnSignal');
const SwitchRoom = new DynamicRoom('Switch');
const StructureRoom = new DynamicRoom('Structure');
const TrackRoom = new DynamicRoom('Track');
const IntersectionRoom = new DynamicRoom('Intersection');
const IntersectionLaneRoom = new DynamicRoom('IntersectionLane');
const IntersectionSwitchingRoom = new DynamicRoom('IntersectionSwitching');
const IntersectionTrafficLightRoom = new DynamicRoom('IntersectionTrafficLight');
const TrafficLightModelRoom = new DynamicRoom('TrafficLightModel');

export { ApiDataRoom };
export { TrainDetailsRoom };
export { TrainListRoom };
export { TransitLineListRoom };
export { TransitLineDetailsRoom };
export { TransitStationListRoom };
export { TransitStationDetailsRoom };
export { TransitSettingsRoom };
export { VersionRoom };
export { TimeRoom };
export { RuntimeRoom };
export { ModuleRoom };
export { SaveSlotRoom };
export { FreeSlotRoom };
export { SignalRoom };
export { WaitingOnSignalRoom };
export { SwitchRoom };
export { StructureRoom };
export { TrackRoom };
export { IntersectionRoom };
export { IntersectionLaneRoom };
export { IntersectionSwitchingRoom };
export { IntersectionTrafficLightRoom };
export { TrafficLightModelRoom };
