import { CeTypes } from '../CeTypes';
import DynamicRoom from './DynamicRoom';

const ApiDataRoom = new DynamicRoom('API Data');
const ApiEntriesRoom = new DynamicRoom(CeTypes.ServerApiEntries);
const ServerStatsRoom = new DynamicRoom(CeTypes.ServerStats);
const RuntimeStatisticsRoom = new DynamicRoom(CeTypes.ServerRuntimeStatistics);
const TrainListRoom = new DynamicRoom('TrainList');
const TrainStaticRoom = new DynamicRoom('TrainStatic');
const TrainDynamicRoom = new DynamicRoom('TrainDynamic');
const RollingStockStaticRoom = new DynamicRoom('RollingStockStatic');
const RollingStockDynamicRoom = new DynamicRoom('RollingStockDynamic');
const TransitLineListRoom = new DynamicRoom('Transit List of Lines');
const TransitLineDetailsRoom = new DynamicRoom('Transit Details of Line');
const TransitStationListRoom = new DynamicRoom('Transit List of Stations');
const TransitStationDetailsRoom = new DynamicRoom('Transit Details of Station');
const TransitSettingsRoom = new DynamicRoom('Transit Settings');

const VersionRoom = new DynamicRoom(CeTypes.HubEepVersion);
const WeatherRoom = new DynamicRoom(CeTypes.HubWeather);
const TimeRoom = new DynamicRoom(CeTypes.HubTime);
const RuntimeRoom = new DynamicRoom(CeTypes.HubRuntime);
const ModuleRoom = new DynamicRoom(CeTypes.HubModule);
const SaveSlotRoom = new DynamicRoom(CeTypes.HubSaveSlot);
const FreeSlotRoom = new DynamicRoom(CeTypes.HubFreeSlot);
const SignalRoom = new DynamicRoom(CeTypes.HubSignal);
const WaitingOnSignalRoom = new DynamicRoom(CeTypes.HubWaitingOnSignal);
const SwitchRoom = new DynamicRoom(CeTypes.HubSwitch);
const StructureRoom = new DynamicRoom(CeTypes.HubStructure);
const RollingStockTexturesRoom = new DynamicRoom('ce.hub.RollingStockTextures');
const RollingStockRotationRoom = new DynamicRoom('ce.hub.RollingStockRotation');
const TrackRoom = new DynamicRoom('Track');
const IntersectionRoom = new DynamicRoom(CeTypes.RoadIntersection);
const IntersectionLaneRoom = new DynamicRoom(CeTypes.RoadIntersectionLane);
const IntersectionSwitchingRoom = new DynamicRoom(CeTypes.RoadIntersectionSwitching);
const IntersectionTrafficLightRoom = new DynamicRoom(CeTypes.RoadIntersectionTrafficLight);
const TrafficLightModelRoom = new DynamicRoom(CeTypes.RoadSignalTypeDefinition);

export { ApiDataRoom };
export { ApiEntriesRoom };
export { ServerStatsRoom };
export { RuntimeStatisticsRoom };
export { TrainListRoom };
export { TrainStaticRoom };
export { TrainDynamicRoom };
export { TransitLineListRoom };
export { TransitLineDetailsRoom };
export { TransitStationListRoom };
export { TransitStationDetailsRoom };
export { TransitSettingsRoom };
export { VersionRoom };
export { WeatherRoom };
export { TimeRoom };
export { RuntimeRoom };
export { ModuleRoom };
export { SaveSlotRoom };
export { FreeSlotRoom };
export { SignalRoom };
export { WaitingOnSignalRoom };
export { SwitchRoom };
export { StructureRoom };
export { RollingStockStaticRoom };
export { RollingStockDynamicRoom };
export { RollingStockTexturesRoom };
export { RollingStockRotationRoom };
export { TrackRoom };
export { IntersectionRoom };
export { IntersectionLaneRoom };
export { IntersectionSwitchingRoom };
export { IntersectionTrafficLightRoom };
export { TrafficLightModelRoom };
