---@meta

---@alias SignalType
---| "BUS"
---| "CAR"
---| "TRAM"
---| "PEDESTRIAN"
---| "BICYCLE"

---@alias LaneRequestType
---| "NICHT VERWENDET"
---| "ANFORDERUNG"
---| "NORMAL"
---| "FUSSGAENGER"

---@alias LaneDirection
---| "LEFT"
---| "HALF-LEFT"
---| "STRAIGHT"
---| "HALF-RIGHT"
---| "RIGHT"

---@alias LaneType
---| "BUS"
---| "CAR"
---| "TRAM"
---| "PEDESTRIAN"
---| "BICYCLE"

---@class TrafficLightModel
---@field name string
---@field signalIndexRed number
---@field signalIndexGreen number
---@field signalIndexYellow number
---@field signalIndexRedYellow number
---@field signalIndexPedestrian number
---@field signalIndexSwitchOff number
---@field signalIndexBlinkYellow number
---@field signalIndexGreenYellow number
---@field allModels table<string, TrafficLightModel>
---@field new fun(self: TrafficLightModel, name: string, signalIndexRed: number, signalIndexGreen: number, signalIndexYellow?: number, signalIndexRedYellow?: number, signalIndexPedestrian?: number, signalIndexSwitchOff?: number, signalIndexBlinkYellow?: number, signalIndexGreenYellow?: number):TrafficLightModel
---@field print fun(self: TrafficLightModel):nil
---@field signalIndexOf fun(self: TrafficLightModel, indication: string):number
---@field indicationOf fun(self: TrafficLightModel, signalIndex: number):string

---@class Signal
---@field type string
---@field vehicleSignalName string|nil
---@field pedestrianSignalName string|nil
---@field use string
---@field signalId number
---@field trafficLightModel TrafficLightModel
---@field lightStructures table
---@field axisStructures table
---@field reason string
---@field lanes table
---@field phase string
---@field debug boolean
---@field phaseInfo any
---@field laneInfo any
---@field laneNameInfo any
---@field new fun(self: Signal, name: string, signalId: number, trafficLightModel: TrafficLightModel, redStructure?: string, greenStructure?: string, yellowStructure?: string, requestStructure?: string):Signal
---@field newPedestrianOnly fun(self: Signal, name: string, signalId: number, trafficLightModel: TrafficLightModel, redStructure?: string, greenStructure?: string, yellowStructure?: string, requestStructure?: string):Signal
---@field withPedestrian fun(self: Signal, pedestrianSignalName: string):Signal
---@field asPedestrianOnly fun(self: Signal):Signal
---@field vehicleSignalNameTippText fun(self: Signal):string
---@field pedestrianSignalNameTippText fun(self: Signal):string
---@field signalNamesTippText fun(self: Signal):string
---@field signalNamesText fun(self: Signal):string
---@field addLightStructure fun(self: Signal, redStructure?: string, greenStructure?: string,
--- yellowStructure?: string, requestStructure?: string):nil
---@field addAxisStructure fun(self: Signal, structureName: string, axisName: string, positionDefault: number,
--- positionRed?: number, positionGreen?: number, positionYellow?: number,
--- positionRedYellow?: number, positionPedestrian?: number):nil
---@field setPhaseInfo fun(self: Signal, phaseInfo: any):nil
---@field setLaneInfo fun(self: Signal, laneInfo: any):nil
---@field setLaneNameInfo fun(self: Signal, laneNameInfo: any):nil
---@field showInfoText fun(self: Signal, showInfo: boolean):nil
---@field changeInfoText fun(self: Signal, infoText: string):nil
---@field refreshInfo fun(self: Signal):nil
---@field switchAll fun(signals: table, indication: string, reason?: string):nil
---@field switchTo fun(self: Signal, indication: string, reason?: string):nil
---@field switchStructureLight fun(self: Signal):nil
---@field switchStructureAxis fun(self: Signal):nil
---@field switchSignal fun(self: Signal, sigIndex: number):nil
---@field showRequestOnSignal fun(self: Signal, hasRequest: boolean):nil
---@field print fun(self: Signal):nil
---@field changed fun(self: Signal):nil
---@field applyToLane fun(self: Signal, lane: Lane, ...: string):Lane

---@class Lane
---@field Directions table<string, LaneDirection>
---@field RequestType table<string, LaneRequestType>
---@field Type table<string, LaneType>
---@field calculatePriority fun(self: Lane, signals: table):number
---@field checkRequests fun(self: Lane):nil
---@field debug boolean
---@field driveOnDefaultSignals fun(self: Lane, ...: TrafficLight):Lane
---@field driveOn fun(self: Lane, signal: Signal, ...: string):Lane
---@field firstGoodTrain string|nil
---@field firstVehiclesRoute string|nil
---@field getLaneType fun(self: Lane):LaneRequestType
---@field getName fun(self: Lane):string
---@field getRequestInfo fun(self: Lane):string
---@field getType fun():string
---@field getVehicleCount fun(self: Lane):number
---@field getVehicleCountRoutes fun(self: Lane, routes: table):number
---@field getWaitCount fun(self: Lane):number
---@field hasRequest fun(self: Lane):boolean
---@field incrementWaitCount fun(self: Lane):nil
---@field laneCanDrive fun(lane: Lane, signals: table):boolean
---@field laneSignal TrafficLight
---@field name string
---@field new fun(self: Lane, name: string, eepSaveId: number, laneSignal: TrafficLight,
--- directions?: string[], trafficType?: string):Lane
---@field queue Queue
---@field requestInfoText string|nil
---@field requestType LaneRequestType
---@field phase SignalIndication
---@field tracksUsedForRequest boolean
---@field fahrzeugMultiplikator number
---@field requestSignals table<string, TrafficLight[]>
---@field resetQueueFromRoadTracks fun(self: Lane):nil
---@field resetQueueFromSignal fun(self: Lane):nil
---@field resetVehicles fun(self: Lane):nil
---@field resetWaitCount fun(self: Lane):nil
--- Starts route-bound drive signal registration. At least one route is required.
---@field routes fun(self: Lane, ...: string):LaneRouteDriveBuilder
---@field routesToCount table
---@field setDirections fun(self: Lane, ...: LaneDirection):nil
---@field setFahrzeugMultiplikator fun(self: Lane, fahrzeugMultiplikator: number):nil
---@field setHighLightingTracks fun(self: Lane, ...: any):nil
---@field setLaneType fun(self: Lane, requestType: LaneRequestType):nil
---@field setTrafficType fun(self: Lane, trafficType: LaneType):nil
---@field showRequestsOnSignalGroups fun(self: Lane, ...: SignalGroup):Lane
--- Indicates lane requests on the given signal, if the signal has
--- a request structure defined. The additional ... parameter contains route
--- names that can be given to indicate requests on these specific routes only.
---@field signalUsedForRequest boolean
---@field switchSignalTo fun(self: Lane, indication: string, grund: string):nil
---@field tracksForHighlighting table
---@field tracksForRequests table
---@field signalChanged fun(self: Lane, signal: Signal):nil
---@field signalsToDriveOn table|nil
---@field type string
---@field useSignalForQueue fun(self: Lane):nil
---@field useTrackForQueue fun(self: Lane, roadId: number):nil
---@field vehicleCount number
---@field vehicleEntered fun(self: Lane, trainName: string):nil
---@field vehicleLeft fun(self: Lane, trainName: string):nil
---@field waitCount number

---@class LaneRouteDriveBuilder
---@field driveOnlyOnSignalGroups fun(self: LaneRouteDriveBuilder, ...: SignalGroup):LaneRouteDriveBuilder
---@field driveAlsoOnSignalGroups fun(self: LaneRouteDriveBuilder, ...: SignalGroup):LaneRouteDriveBuilder
---@field showRequestsOnSignalGroups fun(self: LaneRouteDriveBuilder, ...: SignalGroup):Lane

---@class TrafficPhase
---@field type string
---@field name string
---@field signalHeads table<Signal, SignalType>
---@field greenTimeSeconds number
---@field crossing Intersection|nil
---@field prio number
---@field lanes table<Lane, boolean>
---@field debug boolean
---@field Type table<string, SignalType>
---@field getType fun():string
---@field getName fun(self: TrafficPhase):string
---@field new fun(self: TrafficPhase, name: string, greenTimeSeconds?: number):TrafficPhase
---@field initPhase fun(self: TrafficPhase):nil
---@field signalHeadsToTurnRedAndGreen fun(self: TrafficPhase, oldPhase?: TrafficPhase):
---(table<Signal, SignalType>, table<Signal, SignalType>)
---@field tasksForPhaseChangeFrom fun(self: TrafficPhase, oldPhase?: TrafficPhase, afterRedTask?: any):table
---@field getLanes fun(self: TrafficPhase):table<Lane, boolean>
---@field lanesNamesText fun(self: TrafficPhase):string
---@field addSignalGroup fun(self: TrafficPhase, ...: SignalGroup):nil
---@field lanesSortedByPriority fun(self: TrafficPhase):Lane[]
---@field lanesSortedByName fun(self: TrafficPhase):Lane[]
---@field phasePriorityComparator fun(phase1: TrafficPhase, phase2: TrafficPhase):boolean
---@field calculatePriority fun(self: TrafficPhase):number
---@field resetWaitCount fun(self: TrafficPhase):nil

---@class Intersection
---@field name string
---@field lanes table<string, Lane>
---@field signals table<string, Signal>
---@field currentPhase TrafficPhase
---@field phases TrafficPhase[]
---@field greenPhaseFinished boolean
---@field greenPhaseReached boolean
---@field greenTimeSeconds number
---@field staticCams string[]
---@field nextPhase TrafficPhase|nil
---@field manualPhase string|nil
---@field tippStructure string|nil
---@field switchInStrictOrder boolean
---@field debug boolean
---@field allIntersections table<string, Intersection>
---@field switchManuallyTo fun(crossingName: string, phaseName: string):nil
---@field switchAutomatically fun(crossingName: string):nil
---@field getType fun():string
---@field getName fun(self: Intersection):string
---@field getPhases fun(self: Intersection):TrafficPhase[]
---@field getCurrentPhase fun(self: Intersection):TrafficPhase
---@field getNextPhase fun(self: Intersection):TrafficPhase|nil
---@field getManualPhase fun(self: Intersection):string|nil
---@field onSwitchedToPhase fun(self: Intersection, currentPhase: TrafficPhase):nil
---@field calculateNextPhase fun(self: Intersection):TrafficPhase|nil
---@field setManualPhase fun(self: Intersection, phaseName: string):nil
---@field setAutomaticPhase fun(self: Intersection):nil
---@field setSwitchInStrictOrder fun(self: Intersection, value: boolean):nil
---@field getGreenTimeSeconds fun(self: Intersection):number
---@field setGreenTimeFinished fun(self: Intersection, greenPhaseFinished: boolean):nil
---@field isGreenTimeFinished fun(self: Intersection):boolean
---@field setGreenReached fun(self: Intersection, greenPhaseReached: boolean):nil
---@field isGreenReached fun(self: Intersection):boolean
---@field setTippStructure fun(self: Intersection, tippStructure: string):nil
---@field getStaticCams fun(self: Intersection):string[]
---@field addStaticCam fun(self: Intersection, kameraName: string):nil
---@field resetVehicles fun():nil
---@field new fun(self: Intersection, name: string, greenTimeSeconds?: number):Intersection
---@field newPhase fun(self: Intersection, name: string, greenTimeSeconds?: number):TrafficPhase
---@field addPhase fun(self: Intersection, phase: TrafficPhase):TrafficPhase
---@field updateLaneTipText fun(self: Intersection):nil
---@field initPhases fun():nil
---@field switchPhases fun():nil
