name: CI Tests for Web, Server and Docs

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install via Yarn
        run: yarn install --immutable

      - name: Shared lint
        run: yarn lint:shared

      - name: Web-App lint
        run: yarn lint:app

      - name: Web-Server lint
        run: yarn lint:server

      - name: Server tests
        run: yarn test:server

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build docs
        run: bundle exec jekyll build

  e2e:
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install via Yarn
        run: yarn install --immutable

      - name: Build shared package
        run: yarn workspace @ak/web-shared run build

      - name: Build Web-App preview
        run: yarn workspace @ak/web-app run build

      - name: Build Web-Server
        run: yarn workspace @ak/web-server exec tsc --build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: .
          start: node ./scripts/run-parallel.mjs "yarn workspace @ak/web-server run run:test" "yarn workspace @ak/web-app run run"
          wait-on: 'http://localhost:3000/server'
          record: false
          command: yarn workspace @ak/web-app run test:e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
